# Generated by Django 6.0.7 on 2026-08-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_id',
            new_name='payment_id',
        ),
    ]
