# Generated by Django 6.0.7 on 2026-08-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0003_order_address_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_person',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Preparing', max_length=30),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
